spring:
  application:
    name: Yomozomo

  datasource: # spring 바로 아래 레벨
    url: jdbc:oracle:thin:@localhost:1521:XE # datasource 바로 아래 2칸 들여쓰기
    driver-class-name: oracle.jdbc.OracleDriver
    username: system
    password: 12345

  jpa: # spring 바로 아래 레벨
    hibernate: # jpa 바로 아래 레벨
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

  sql: # spring 바로 아래 레벨
    init: # sql 바로 아래 레벨
      mode: embedded