spring:
  application:
    name: Yomozomo

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: system
    password: 12345

  jpa:
    hibernate:
      ddl-auto: validate # 또는 none
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

  sql:
    init:
      mode: embedded # 또는 never